# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='joined',
            field=models.ManyToManyField(related_name='joined', to='travel_buddy.User'),
        ),
    ]
