# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0002_auto_20171124_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='travel_buddy.User'),
        ),
    ]
